[tool.poetry]
name = "ragnar-whitewolf"
version = "0.1.0"
description = ""
authors = ["Ragnar <ragnarwhitewolf@pm.me>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
